"""The client plane — an always-on local control surface for chief (#128).

Whenever chief runs it binds a unix-domain socket speaking LF-delimited JSON frames
(:mod:`chief.client_plane.protocol`), independent of any chat platform: a chief with
zero platform tokens still boots with just the socket. :class:`SocketServer` owns the
listener's lifecycle and dispatches inbound frames to a pluggable handler (the #131 CLI
adapter installs one); the #132 client imports only the protocol vocabulary.
"""

from .protocol import (
    CARD_OPTIONS,
    CLI_PLATFORM,
    DEFAULT_THREAD_KEY,
    MILESTONE_PREFIX,
    PROTOCOL_VERSION,
    TYPE_ANSWER,
    TYPE_BACKFILL,
    TYPE_CARD,
    TYPE_CARD_RESOLVED,
    TYPE_COMMAND,
    TYPE_ERROR,
    TYPE_FILE,
    TYPE_HELLO,
    TYPE_LIST_THREADS,
    TYPE_MILESTONE,
    TYPE_PING,
    TYPE_PONG,
    TYPE_REPLY,
    TYPE_SKILLS,
    TYPE_SKILLS_LIST,
    TYPE_STATUS,
    TYPE_STATUS_SNAPSHOT,
    TYPE_SWITCH,
    TYPE_THREADS,
    TYPE_USER,
    FrameError,
    answer_frame,
    backfill_frame,
    card_frame,
    card_resolved_frame,
    command_frame,
    decode,
    encode,
    error_frame,
    file_frame,
    hello_frame,
    list_threads_frame,
    milestone_frame,
    outbound_frame,
    pong_frame,
    reply_frame,
    skills_frame,
    skills_list_frame,
    status_frame,
    status_snapshot_frame,
    switch_frame,
    threads_frame,
    user_frame,
)
from .server import ConnectHook, FrameHandler, FrameSender, SocketServer

__all__ = [
    "CARD_OPTIONS",
    "CLI_PLATFORM",
    "DEFAULT_THREAD_KEY",
    "MILESTONE_PREFIX",
    "PROTOCOL_VERSION",
    "TYPE_ANSWER",
    "TYPE_BACKFILL",
    "TYPE_CARD",
    "TYPE_CARD_RESOLVED",
    "TYPE_COMMAND",
    "TYPE_ERROR",
    "TYPE_FILE",
    "TYPE_HELLO",
    "TYPE_LIST_THREADS",
    "TYPE_MILESTONE",
    "TYPE_PING",
    "TYPE_PONG",
    "TYPE_REPLY",
    "TYPE_SKILLS",
    "TYPE_SKILLS_LIST",
    "TYPE_STATUS",
    "TYPE_STATUS_SNAPSHOT",
    "TYPE_SWITCH",
    "TYPE_THREADS",
    "TYPE_USER",
    "ConnectHook",
    "FrameError",
    "FrameHandler",
    "FrameSender",
    "SocketServer",
    "answer_frame",
    "backfill_frame",
    "card_frame",
    "card_resolved_frame",
    "command_frame",
    "decode",
    "encode",
    "error_frame",
    "file_frame",
    "hello_frame",
    "list_threads_frame",
    "milestone_frame",
    "outbound_frame",
    "pong_frame",
    "reply_frame",
    "skills_frame",
    "skills_list_frame",
    "status_frame",
    "status_snapshot_frame",
    "switch_frame",
    "threads_frame",
    "user_frame",
]
