#!/usr/bin/env bash
# chief installer — host-native.
#
# Core runs natively on this machine; only the MCP sidecars (Google servers,
# playwright) live in docker compose. This script checks prerequisites, scaffolds
# the config/secrets/data layout, installs Python deps, runs the DB migrations,
# optionally builds + starts the sidecar containers, and installs a `chief`
# launcher. macOS (bash 3.2) and Linux compatible.
#
# Usage:
#   ./install.sh [--google] [--playwright]
#
#   --google      build + start the Google MCP sidecars (compose profile "google")
#   --playwright  build + start the browser sidecar (compose profile "playwright")

set -euo pipefail

REPO_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
cd "$REPO_DIR"

WITH_GOOGLE=0
WITH_PLAYWRIGHT=0
for arg in "$@"; do
  case "$arg" in
    --google) WITH_GOOGLE=1 ;;
    --playwright) WITH_PLAYWRIGHT=1 ;;
    -h|--help)
      sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "unknown flag: $arg (try --help)" >&2; exit 2 ;;
  esac
done

say()  { printf '\033[1m==> %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
miss() { printf '  \033[33m✗\033[0m %s\n' "$*"; }

fail() { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ---- prerequisites -----------------------------------------------------------
say "checking prerequisites"
command -v git >/dev/null 2>&1 || fail "git is required (https://git-scm.com)"
ok "git"
command -v uv >/dev/null 2>&1 || fail "uv is required (https://docs.astral.sh/uv/)"
ok "uv"
command -v docker >/dev/null 2>&1 \
  || fail "docker is required for the MCP sidecars (https://docs.docker.com)"
docker compose version >/dev/null 2>&1 \
  || fail "docker compose v2 is required ('docker compose' not found)"
ok "docker + compose"

# ---- repo layout -------------------------------------------------------------
say "scaffolding directories"
git submodule update --init --recursive
mkdir -p data/screenshots data/workspace secrets/google_tokens
ok "data/ (sqlite, audit log, memory, workspace, screenshots — gitignored)"
ok "secrets/ (one file per secret — gitignored)"

# ---- secrets checklist -------------------------------------------------------
# Missing secrets are reported, never fabricated: an empty token file would just
# turn a clear boot error into a confusing API failure.
say "checking secrets (files under ./secrets/, or env vars of the same name)"
SECRETS_OK=1
if [ -s secrets/claude_code_oauth_token ] || [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  ok "claude_code_oauth_token"
else
  SECRETS_OK=0
  miss "claude_code_oauth_token — run 'claude setup-token' and save the token to secrets/claude_code_oauth_token"
fi
if [ -s secrets/telegram_bot_token ] || [ -n "${TELEGRAM_BOT_TOKEN:-}" ] \
  || [ -s secrets/discord_bot_token ] || [ -n "${DISCORD_BOT_TOKEN:-}" ]; then
  ok "chat platform token (telegram and/or discord)"
else
  SECRETS_OK=0
  miss "no chat platform token — save a bot token to secrets/telegram_bot_token (BotFather) or secrets/discord_bot_token, and set the matching owner id in config.yaml"
fi

# ---- python deps + migrations --------------------------------------------------
say "installing python dependencies (uv sync)"
uv sync

say "running database migrations"
uv run python - <<'PY'
import os

import yaml

from chief.persistence.db import _run_migrations

with open("config.yaml", encoding="utf-8") as fh:
    db_path = yaml.safe_load(fh).get("db_path", "data/chief.db")
db_path = os.path.expanduser(os.environ.get("DB_PATH", db_path))
parent = os.path.dirname(db_path)
if parent:
    os.makedirs(parent, exist_ok=True)
_run_migrations(db_path)
print(f"  migrations applied: {db_path}")
PY

# ---- MCP sidecars ---------------------------------------------------------------
# (plain string, not an array: empty-array expansion trips set -u on macOS bash 3.2)
PROFILE_FLAGS=""
if [ "$WITH_GOOGLE" = 1 ]; then
  PROFILE_FLAGS="$PROFILE_FLAGS --profile google"
fi
if [ "$WITH_PLAYWRIGHT" = 1 ]; then
  PROFILE_FLAGS="$PROFILE_FLAGS --profile playwright"
fi
if [ -n "$PROFILE_FLAGS" ]; then
  say "building + starting MCP sidecars ($PROFILE_FLAGS)"
  # shellcheck disable=SC2086 — deliberate word-splitting of the flag string
  docker compose $PROFILE_FLAGS up -d --build
else
  say "skipping MCP sidecars (pass --google / --playwright to start them)"
fi

# ---- launcher -------------------------------------------------------------------
say "installing the 'chief' launcher"
BIN_DIR="${HOME}/.local/bin"
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/chief" <<EOF
#!/usr/bin/env bash
# Launcher for the host-native chief core (generated by install.sh).
cd "$REPO_DIR" && exec uv run python -m chief.entrypoint "\$@"
EOF
chmod +x "$BIN_DIR/chief"
ok "$BIN_DIR/chief"
case ":$PATH:" in
  *":$BIN_DIR:"*) : ;;
  *) miss "$BIN_DIR is not on your PATH — add it, or run: uv run python -m chief.entrypoint" ;;
esac

# ---- summary ----------------------------------------------------------------------
say "done"
if [ "$SECRETS_OK" = 1 ]; then
  echo "  run 'chief' to start (or: uv run python -m chief.entrypoint)"
else
  echo "  finish the secrets checklist above, then run 'chief' to start"
fi
echo "  config: config.yaml (owner ids, enabled services, blacklist, screening)"
echo "  google: mint the shared token once with 'uv run python -m chief.tools.google.auth'"
